-- =========================================================
-- TERRA — SQL des tables MÉTIER (à exécuter dans Supabase)
--
-- ⚠️ ÉTAPE MANUELLE OBLIGATOIRE :
-- Copiez tout ce fichier dans l'éditeur SQL de Supabase
-- (Dashboard → SQL Editor → New query) et exécutez-le UNE fois.
-- Le backend ne crée jamais de table lui-même.
--
-- Conventions reprises de la base existante :
--   - clés étrangères nommées id_<table>  (ex. id_administrateur)
--   - horodatage de création : cree_le
-- =========================================================

-- ---------------------------------------------------------
-- 1) AGRICULTEUR — on ajoute l'email (copie de auth.users)
--    pour que l'admin voie la liste sans interroger Auth.
-- ---------------------------------------------------------
alter table agriculteur add column if not exists email text;
alter table agriculteur add column if not exists cree_le timestamptz default now();

-- ---------------------------------------------------------
-- 2) PARCELLE — gérée par un agriculteur
--    jour_actuel n'est PAS stocké : il se calcule à partir de
--    date_plantation (aujourd'hui - date_plantation).
-- ---------------------------------------------------------
create table if not exists parcelle (
  id              bigint generated by default as identity primary key,
  id_agriculteur  bigint not null references agriculteur(id) on delete cascade,
  nom             text not null,
  culture         text not null default 'Tomate',
  superficie      double precision,            -- hectares (optionnel)
  date_plantation date not null,               -- saisie par l'agriculteur
  lat             double precision,            -- pour la météo localisée
  lon             double precision,
  etat            text not null default 'active',  -- active | archivee
  cree_le         timestamptz default now()
);
create index if not exists idx_parcelle_agriculteur on parcelle (id_agriculteur);

-- ---------------------------------------------------------
-- 3) CAPTEUR — installé sur une parcelle
--    etat : actif | hors_ligne | panne | maintenance
-- ---------------------------------------------------------
create table if not exists capteur (
  id            bigint generated by default as identity primary key,
  id_parcelle   bigint not null references parcelle(id) on delete cascade,
  nom           text not null,                 -- ex. « Sonde humidité du sol »
  type          text not null,                 -- humidite_sol | temperature_air | humidite_air | pluie
  unite         text,                          -- % | °C | mm
  etat          text not null default 'actif',
  batterie      int,                           -- % restant (optionnel)
  emplacement   text,                          -- ex. « Zone racinaire — rang 3 »
  derniere_comm timestamptz default now(),     -- dernière communication reçue
  cree_le       timestamptz default now()
);
create index if not exists idx_capteur_parcelle on capteur (id_parcelle);

-- ---------------------------------------------------------
-- 4) ALERTE — la table existe déjà (id, date, etat, id_administrateur) ;
--    on la complète pour le signalement de capteurs par l'agriculteur.
--    etat : en_attente | en_intervention | repare | cloture
-- ---------------------------------------------------------
alter table alerte add column if not exists texte text;
alter table alerte add column if not exists id_capteur bigint references capteur(id) on delete cascade;
alter table alerte add column if not exists id_agriculteur bigint references agriculteur(id) on delete set null;

-- Correctif : la colonne etat utilisait un enum défectueux
-- (« etat_capteur » ne contenait qu'une valeur : 'active, en_panne').
-- On la repasse en texte — voir db/fix_alerte_etat.sql pour le détail.
alter table alerte alter column etat drop default;
alter table alerte alter column etat type text using etat::text;
alter table alerte alter column etat set default 'en_attente';
drop type if exists etat_capteur;

-- ---------------------------------------------------------
-- 5) MESURE — envoyée par un capteur (fictive pour l'instant,
--    réelle quand les capteurs IoT seront prêts).
--    donnees (jsonb) : { "valeur": 54.2, "unite": "%" }
-- ---------------------------------------------------------
create table if not exists mesure (
  id         bigint generated by default as identity primary key,
  id_capteur bigint not null references capteur(id) on delete cascade,
  date       timestamptz not null default now(),
  donnees    jsonb not null
);
-- Chemin chaud : « dernières mesures d'un capteur »
create index if not exists idx_mesure_capteur_date on mesure (id_capteur, date desc);

-- ---------------------------------------------------------
-- 6) PRESCRIPTION — concerne une parcelle (fictive pour l'instant,
--    générée par le Moteur Expert plus tard).
--    etat : a_faire | faite | ignoree
-- ---------------------------------------------------------
create table if not exists prescription (
  id            bigint generated by default as identity primary key,
  id_parcelle   bigint not null references parcelle(id) on delete cascade,
  date          date not null default current_date,
  action        text not null,                 -- ex. « Irriguer 18 L/m² »
  justification text,
  volume_eau    double precision default 0,    -- L/m²
  priorite      text default 'moyenne',        -- haute | moyenne | basse
  etat          text not null default 'a_faire',
  date_faite    date,
  cree_le       timestamptz default now()
);
create index if not exists idx_prescription_parcelle on prescription (id_parcelle, date desc);

-- ---------------------------------------------------------
-- 7) PROFIL_CULTURE — structure seulement, VOUS remplirez les
--    lignes vous-même (stades de la tomate, Kc, seuils…).
--    Le Moteur Expert s'en servira ensuite.
-- ---------------------------------------------------------
create table if not exists profil_culture (
  id           bigint generated by default as identity primary key,
  culture      text not null default 'Tomate',
  stade        text not null,                  -- ex. « Floraison »
  debut_jour   int not null,                   -- jour de début du stade (inclus)
  fin_jour     int not null,                   -- jour de fin du stade (exclus)
  kc           double precision,               -- coefficient cultural FAO
  seuil_bas    double precision,               -- % humidité déclenchant l'irrigation
  seuil_cible  double precision,               -- % humidité visé après irrigation
  humidite_min double precision,
  humidite_max double precision
);
