name: Keep Render Alive
on:
  schedule:
    - cron: "*/14 * * * *" # Toutes les 14 minutes
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping backend
        run: curl -s https://terra-9fg4.onrender.com/api/v1/meteo/previsions > /dev/null
